tsubame_validation = true

[connection]
host = "tsubame"

[sync.code]
from = "~/prog/csi_to_image"
to = "~"
excludes = [".*", "__*", "lightning_logs", "env"]

[exec]
cmd = ["python -m src.encoder.training_cnn_3upsamples -p /gs/fs/tga-nlab/eshan/csi_image_data/datasets/mmfi_hands_two -n $name --epochs 1000 -b 32 --base-channels 2048",
]
max_runtime = "10:00:00"
name = "mmfi_two_cnn_vaelike_noenc_2048"
group = "tga-nlab"

[exec.env]
dir = "csi_to_image" # required, directory from which to run cmd
modules = ["intel", "cuda"]
python_deps = [
"torch",
"torchvision",
"numpy",
"diffusers",
"transformers",
"accelerate",
"lightning",
"more-itertools"
]
env_vars = {PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True"}

[exec.resource]
type = "gpu_1"
count = 1
