services:
  training_server:
    image: "latentcsi"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    volumes:
      - ".:/workspace"
    network_mode: host
    ports:
      - "9000:9000"
    command: "python3.11 -m demo.server.server"
    stdin_open: true
    tty: true

  client_server:
    image: "latentcsi"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    volumes:
      - ".:/workspace"
    network_mode: host
    ports:
      - "8000:8000"
    command: "python3.11 -m demo.client.webserver.main"
    stdin_open: true
    tty: true

  ae_server:
    image: jetson-uv-diffusers
    runtime: nvidia
    volumes:
      - ".:/workspace"
      - "/home/esrh/trt:/trt"
    ports:
      - "8000:8000"
    command: "python3 -m demo.edge.ae_server"
    stdin_open: true
    tty: true
