services:
  training_server:
    image: "csi_image"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    volumes:
      - "/home/esrh/trt:/trt"
    ports:
      - "9999:9999"
    command: "python3 -m src.realtime.server"
    stdin_open: true
    tty: true

  ae_server:
    image: jetson-uv-diffusers
    runtime: nvidia
    volumes:
      - ".:/workspace"
      - "/home/esrh/trt:/trt"
    ports:
      - "8000:8000"
    command: "python3 -m demo.edge.server"
    stdin_open: true
    tty: true
